# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VocabularyEnglish' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  pod 'InstantSearchVoiceOverlay'
  pod 'IQKeyboardManagerSwift'
  pod 'lottie-ios'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
  target 'VocabularyEnglishTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VocabularyEnglishUITests' do
    # Pods for testing
  end

end
