# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SideMenu_Animation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SideMenu'
  pod 'Comets'

  target 'SideMenu_AnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SideMenu_AnimationUITests' do
    # Pods for testing
  end

end
