//
//  ViewController.swift
//  ScrollViewDemo
//
//  Created by Cata on 9/13/20.
//  Copyright © 2020 Cata. All rights reserved.
//

import UIKit

class ViewController: UIViewController {
    @IBOutlet weak var nameLabel: UILabel!
    
    @IBOutlet weak var tenLabel: UILabel!
    override func viewDidLoad() {
        super.viewDidLoad()
        tenLabel.text = "hello"
        
        nameLabel.text = "sdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfkldssdjfsdfjlksjflkjsljfklsjlkfjlskjdfklsdfjlksjljsdlkfjslkjfsldjflsdjflksjflsjdflkdsjlfjdlfjsdlfjsljfklds"
    }


}

