# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SlideTabBarDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'XLPagerTabStrip'

  target 'SlideTabBarDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SlideTabBarDemoUITests' do
    # Pods for testing
  end

end
