# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Menu' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SideMenu'

  target 'MenuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MenuUITests' do
    # Pods for testing
  end

end
